---
- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- include: setup-debian.yml
  when: ansible_os_family == "Debian"

- name: create quagga daemon configuration
  template: >-
    src=quagga.j2
    dest=/etc/quagga/{{ item.key }}.conf
    owner={{ quagga_uid }}
    group={{ quagga_gid }}
    mode=0640
    backup=yes
  with_dict: "{{ quagga_conf }}"
  notify:
    - restart quagga (RedHat)
    - restart quagga (Debian)

- include: services-redhat.yml
  when: ansible_os_family == "RedHat"

- include: services-debian.yml
  when: ansible_os_family == "Debian"
